import esbuild from 'esbuild';
import process from 'node:process';
import { builtinModules as builtins } from 'node:module';

const prod = process.argv.includes('production');
const spike = process.argv.includes('spike');

const banner = `/*
Generated by esbuild. Do not edit. Source: https://github.com/N23eos/vault_telegram_bridge
*/`;

/**
 * Fail the build if anything reaches for a Node or Electron builtin. TZ §1
 * forbids them outright and `isDesktopOnly: false` makes them fatal on mobile.
 * `platform: 'browser'` already refuses to resolve them; this turns the
 * resolution error into a message that says why.
 */
const forbidNodeBuiltins = {
  name: 'forbid-node-builtins',
  setup(build) {
    const forbidden = new Set([...builtins, 'electron', ...builtins.map((m) => `node:${m}`)]);
    build.onResolve({ filter: /.*/ }, (args) => {
      if (forbidden.has(args.path)) {
        return {
          errors: [
            {
              text: `Forbidden import "${args.path}" from ${args.importer}. TZ §1: no Node/Electron API in runtime code (isDesktopOnly: false).`,
            },
          ],
        };
      }
      return null;
    });
  },
};

/**
 * The product bundle must not contain GramJS. It is a devDependency, used only
 * by the throwaway Phase 0 spike, and it costs 722 KB (docs/SPIKE-REPORT.md
 * 0.1-F2). Account mode arrives in v0.3, at which point this guard is revisited
 * along with the lazy-import requirement in 0.1-F7.
 */
const forbidGramjs = {
  name: 'forbid-gramjs',
  setup(build) {
    build.onResolve({ filter: /^telegram(\/|$)/ }, (args) => ({
      errors: [
        {
          text: `The product bundle must not import GramJS ("${args.path}" from ${args.importer}). Bot mode ships in v0.1 — see docs/ADR-001-bot-mode-first.md.`,
        },
      ],
    }));
  },
};

const entry = spike ? 'spikes/src/main.ts' : 'src/main.ts';
const outfile = spike ? 'spikes/dist/main.js' : 'main.js';

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: [entry],
  bundle: true,
  platform: 'browser',
  external: ['obsidian'],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile,
  minify: prod,
  metafile: true,
  plugins: spike ? [forbidNodeBuiltins] : [forbidNodeBuiltins, forbidGramjs],
});

if (prod) {
  const result = await ctx.rebuild();
  const out = Object.values(result.metafile.outputs)[0];
  console.log(`\n${outfile}: ${(out.bytes / 1024).toFixed(1)} KB minified`);
  process.exit(0);
} else {
  await ctx.watch();
}
